In [4]:
import pandas as pd 
import numpy as np
df=pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df['Survived'].mean()

0.3838383838383838

In [8]:
pd.crosstab(df['Sex'],df['Survived'])

Survived    0    1
Sex
female     81  233
male      468  109

In [15]:
# loading data
import numpy as np
import pandas as pd
df=pd.read_csv("Titanic-dataset.csv")
print("\nFirst 5 rows:")
print(df.head())
print("\nInfo about coulmns:")
print(df.info())
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nOverall survival rate")
print(df['Survived'].mean())

First 5 rows:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Info about coulmns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Missing values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Overall survival rate
0.3838383838383838

In [19]:
#cleaning data
df_clean=df.copy()
df_clean['Age']=df_clean.groupby(['Pclass','Sex'])['Age'].transform(lambda x:x.fillna(x.median()))
df_clean['Embarked'].fillna(df_clean['Embarked'].mode()[0],inplace=True)
df_clean['FamilySize']=df_clean['SibSp']+df_clean['Parch']+1
df_clean['IsAlone']=np.where(df_clean['FamilySize']==1,1,0)
df_clean['Title']=df['Name'].str.extract('([A-Za-z]+)\.',expand=False)
df_clean['Title']=df_clean['Title'].replace(['Lady','Countness','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona'],'Rare')
df_clean['Title']=df_clean['Title'].replace('Mlle','Miss')
df_clean['Title']=df_clean['Title'].replace('Ms','Miss')
df_clean['Title']=df_clean['Title'].replace('Mme','Mrs')
df_clean.drop(['Cabin','Ticket','PassengerId','Name'],axis=1,inplace=True)
print("Missing values after cleaning:")
print(df_clean.isnull().sum())

Missing values after cleaning:
Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked      0
FamilySize    0
IsAlone       0
Title         0
dtype: int64

In [38]:
print(df_clean.columns.tolist())
print(df_clean.head(1))

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'FamilySize', 'IsAlone', 'Embarked_Q', 'Embarked_S', 'Title_Master', 'Title_Miss', 'Title_Mr', 'Title_Mrs', 'Title_Rare']
   Survived  Pclass  Sex   Age  SibSp  Parch  Fare  FamilySize  IsAlone  \
0         0       3  NaN  22.0      1      0  7.25           2        0

   Embarked_Q  Embarked_S  Title_Master  Title_Miss  Title_Mr  Title_Mrs  \
0           0           1             0           0         1          0

   Title_Rare
0           0

In [28]:
import sys
print(sys.version)

3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]

In [31]:
import sys
import subprocess
subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'scikit-learn==1.0.2'])

0

In [2]:
# loading data
import numpy as np
import pandas as pd
df=pd.read_csv("Titanic-dataset.csv")
print("\nFirst 5 rows:")
print(df.head())
print("\nInfo about coulmns:")
print(df.info())
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nOverall survival rate")
print(df['Survived'].mean())
#cleaning data
df_clean=df.copy()
df_clean['Age']=df_clean.groupby(['Pclass','Sex'])['Age'].transform(lambda x:x.fillna(x.median()))
df_clean['Embarked'].fillna(df_clean['Embarked'].mode()[0],inplace=True)
df_clean['FamilySize']=df_clean['SibSp']+df_clean['Parch']+1
df_clean['IsAlone']=np.where(df_clean['FamilySize']==1,1,0)
df_clean['Title']=df['Name'].str.extract('([A-Za-z]+)\.',expand=False)
df_clean['Title']=df_clean['Title'].replace(['Lady','Countness','Capt','Col','Don','Dr','Major','Rev','Sir','Jonkheer','Dona'],'Rare')
df_clean['Title']=df_clean['Title'].replace('Mlle','Miss')
df_clean['Title']=df_clean['Title'].replace('Ms','Miss')
df_clean['Title']=df_clean['Title'].replace('Mme','Mrs')
df_clean.drop(['Cabin','Ticket','PassengerId','Name'],axis=1,inplace=True)
print("Missing values after cleaning:")
print(df_clean.isnull().sum())
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
df_clean['Sex']=df_clean['Sex'].map({'male':0,'female':1})
df_clean=pd.get_dummies(df_clean,columns=['Embarked','Title'],drop_first=True)
y=df_clean['Survived']
X=df_clean.drop('Survived',axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
predictions=model.predict(X_test)
print("Model Accuracy:",accuracy_score(y_test,predictions))
print("\nDetailed Report:")
print(classification_report(y_test,predictions))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test,predictions))

First 5 rows:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Info about coulmns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Missing values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Overall survival rate
0.3838383838383838
Missing values after cleaning:
Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked      0
FamilySize    0
IsAlone       0
Title         0
dtype: int64
Model Accuracy: 0.8212290502793296

Detailed Report:
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       105
           1       0.78      0.78      0.78        74

    accuracy                           0.82       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.82      0.82      0.82       179


Confusion Matrix:
[[89 16]
 [16 58]]